<?php

namespace Cradle\Package\System;

use PHPUnit\Framework\TestCase;

use Cradle\Package\PackageHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Cradle_Package_System_Events_Model_Test extends TestCase
{
  /**
   * @var Package
   */
  protected $object;

  public function setUp()
  {
    //this is the OOP version of cradle
    $this->object = new PackageHandler;
    $testRoot = dirname(__DIR__);
    $packageRoot = dirname($testRoot);

    //set the schema folder
    Schema::setFolder($testRoot . '/assets/config/schema');

    //now register system
    $this->object->register('cradlephp/cradle-system', $packageRoot);

    $cradle = $this->object;

    $cradle('event')->on('system-store-insert', function($request, $response) {
      $response->setError(true, 'Insert stub defined');
      $response->setResults($request->getStage());
    });

    $cradle('event')->on('system-store-delete', function($request, $response) {
      $response->setError(true, 'Delete stub defined');
      $response->setResults($request->getStage());
    });

    $cradle('event')->on('system-store-search', function($request, $response) {
      $response->setError(false)->setResults([
        [
          'profile_id' => 2,
          'profile_name' => 'George',
          'profile_gender' => 'male',
          'profile_bio' => 'I am a giant.',
          'profile_birthday' => '1981-12-18',
          'profile_active' => 1,
          'profile_created' => '2020-01-01 00:00:00',
          'profile_updated' => '2020-01-01 00:00:00'
        ]
      ]);
    });

    $cradle('event')->on('system-store-update', function($request, $response) {
      $response->setError(true, 'Update stub defined');
      $response->setResults($request->getStage());
    });
  }

  /**
   */
  public function testCreate()
  {
    $cradle = $this->object;
    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema' => 'profile',
      'profile_name' => 'foo'
    ]);

    $cradle('event')->emit(
      'system-model-create',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue($payload['response']->isError());
    $this->assertEquals('Insert stub defined', $payload['response']->getMessage());
    $this->assertEquals('profile', $payload['response']->getResults('table'));
  }

  /**
   */
  public function testLink()
  {
    $cradle = $this->object;
    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema1' => 'product',
      'schema2' => 'profile',
      'product_id' => 1,
      'profile_id' => 2
    ]);

    $cradle('event')->emit(
      'system-model-link',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue($payload['response']->isError());
    $this->assertEquals('Insert stub defined', $payload['response']->getMessage());
    $this->assertEquals('product_profile', $payload['response']->getResults('table'));
    $this->assertEquals(1, $payload['response']->getResults('rows', 0, 'product_id'));
    $this->assertEquals(2, $payload['response']->getResults('rows', 0, 'profile_id'));

    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema1' => 'product',
      'schema2' => 'profile',
      'product_id' => 1,
      'profile_id' => [4, 5, 6]
    ]);

    $cradle('event')->emit(
      'system-model-link',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue($payload['response']->isError());
    $this->assertEquals('Insert stub defined', $payload['response']->getMessage());
    $this->assertEquals('product_profile', $payload['response']->getResults('table'));

    $this->assertEquals(1, $payload['response']->getResults('rows', 0, 'product_id'));
    $this->assertEquals(4, $payload['response']->getResults('rows', 0, 'profile_id'));
    $this->assertEquals(1, $payload['response']->getResults('rows', 1, 'product_id'));
    $this->assertEquals(5, $payload['response']->getResults('rows', 1, 'profile_id'));
    $this->assertEquals(1, $payload['response']->getResults('rows', 2, 'product_id'));
    $this->assertEquals(6, $payload['response']->getResults('rows', 2, 'profile_id'));
  }

  /**
   */
  public function testDetail()
  {
    $cradle = $this->object;
    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema' => 'profile',
      'profile_id' => 2
    ]);

    $cradle('event')->emit(
      'system-model-detail',
      $payload['request'],
      $payload['response']
    );

    $this->assertEquals('Search stub defined', $payload['response']->getMessage());
    $this->assertEquals('George', $payload['response']->getResults('profile', 'profile_name'));
  }

  /**
   */
  public function testRemove()
  {
    $cradle = $this->object;
    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema' => 'profile',
      'profile_id' => 2
    ]);

    $cradle('event')->emit(
      'system-model-remove',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue($payload['response']->isError());
    $this->assertEquals('Update stub defined', $payload['response']->getMessage());
    $this->assertEquals('profile', $payload['response']->getResults('table'));
    $this->assertEquals('profile_id = %s', $payload['response']->getResults('filters', 0, 'where'));
    $this->assertEquals(2, $payload['response']->getResults('filters', 0, 'binds', 0));
    $this->assertEquals(0, $payload['response']->getResults('data', 'profile_active'));
  }

  /**
   */
  public function testRestore()
  {
    $cradle = $this->object;
    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema' => 'profile',
      'profile_id' => 2
    ]);

    $cradle('event')->emit(
      'system-model-restore',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue($payload['response']->isError());
    $this->assertEquals('Update stub defined', $payload['response']->getMessage());
    $this->assertEquals('profile', $payload['response']->getResults('table'));
    $this->assertEquals('profile_id = %s', $payload['response']->getResults('filters', 0, 'where'));
    $this->assertEquals(2, $payload['response']->getResults('filters', 0, 'binds', 0));
    $this->assertEquals(1, $payload['response']->getResults('data', 'profile_active'));
  }

  /**
   */
  public function testUnlink()
  {
    $cradle = $this->object;
    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema1' => 'product',
      'schema2' => 'profile',
      'product_id' => 1,
      'profile_id' => 2
    ]);

    $cradle('event')->emit(
      'system-model-unlink',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue($payload['response']->isError());
    $this->assertEquals('Delete stub defined', $payload['response']->getMessage());
    $this->assertEquals('product_profile', $payload['response']->getResults('table'));
    $this->assertEquals('(product_id = 1 AND profile_id = 2)', $payload['response']->getResults('filter', 0, 'where'));

    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema1' => 'product',
      'schema2' => 'profile',
      'product_id' => 1,
      'profile_id' => [4, 5, 6]
    ]);

    $cradle('event')->emit(
      'system-model-unlink',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue($payload['response']->isError());
    $this->assertEquals('Delete stub defined', $payload['response']->getMessage());
    $this->assertEquals('product_profile', $payload['response']->getResults('table'));
    $this->assertEquals('(product_id = 1 AND profile_id = 4) OR (product_id = 1 AND profile_id = 5) OR (product_id = 1 AND profile_id = 6)', $payload['response']->getResults('filter', 0, 'where'));
  }

  /**
   */
  public function testUpdate()
  {
    $cradle = $this->object;
    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage([
      'schema' => 'profile',
      'profile_id' => 2,
      'profile_name' => 'foo',
    ]);

    $cradle('event')->emit(
      'system-model-update',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue($payload['response']->isError());
    $this->assertEquals('Update stub defined', $payload['response']->getMessage());
    $this->assertEquals('profile', $payload['response']->getResults('table'));
    $this->assertEquals('profile_id = %s', $payload['response']->getResults('filters', 0, 'where'));
    $this->assertEquals(2, $payload['response']->getResults('filters', 0, 'binds', 0));
    $this->assertEquals('foo', $payload['response']->getResults('data', 'profile_name'));
    $this->assertTrue(isset($payload['response']->getResults('data')['profile_updated']));
    $this->assertFalse(isset($payload['response']->getResults('data')['profile_created']));
    $this->assertFalse(isset($payload['response']->getResults('data')['profile_gender']));
  }
}
