<?php

namespace Cradle\Package\System;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Cradle_Package_System_Schema_Events_Test extends TestCase
{
  /**
   * @var Package
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = cradle()->register('pdo');

    cradle('global')->path('config', dirname(__DIR__) . '/assets/config');
    cradle('global')->path('schema', dirname(__DIR__) . '/assets/config/schema');

    $this->object
      ->package('pdo')
      ->mapPackageMethods(include dirname(__DIR__) . '/assets/mysql.php');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   */
  public function testCreate()
  {
    $cradle = $this->object;
    $payload = $cradle('io')->makePayload(false);
    $payload['request']->setStage(include dirname(__DIR__) . '/assets/post.php');
    $cradle('event')->emit('system-schema-create', $payload['request'], $payload['response']);

    print_r($payload['response']->get('json'));
  }
}
